# Use this file to templatize your application's native configuration files.
# See the docs at https://www.habitat.sh/docs/create-packages-configure/.
# You can safely delete this file if you don't need it.

etcd-name = "default"
etcd-data-dir = "data"

etcd-client-end = 2379
etcd-server-end = 2380

etcd-auto-tls = "false"
etcd-http-proto = "https"

etcd-discovery = ""

etcd-listen-host-ip = ""

etcd-initial-cluster = ""

etcd-client-cert-auth = "true"
etcd-peer-client-cert-auth = "true"
# As this is my wrapper, I can hardcode things like this...
etcd-client-cert-path = "/hab/svc/kube-certificates/files"
etcd-peer-client-cert-path = "/hab/svc/kube-certificates/files"

etcd-listen-client-urls = "http://0.0.0.0"
etcd-listen-peer-urls = "http://0.0.0.0"
etcd-advertise-client-urls = "http://0.0.0.0"
etcd-initial-advertise-peer-urls = "http://0.0.0.0"

etcd-initial-cluster-state = "new"
etcd-initial-cluster-token = "etcd-cluster-0"
