#
# https://www.vaultproject.io/intro/getting-started/dev-server.html
[dev]
mode = false

[storage]
engine = "etcd"
#location = "127.0.0.1"
location = "vault-etcd"
#port = "8500"
#path = "vault"

[storage.tls]
enabled = true
cert_file = "{{pkg.svc_files_path}}/vault-client.pem"
key_file = "{{pkg.svc_files_path}}/vault-client-key.pem"
ca_file = "{{pkg.svc_files_path}}/ca.pem"

[listener]
#type = "tcp"
#location = "127.0.0.1"
location = "0.0.0.0"
#port = "8200"
tls_disable = "0"

[listener.tls]
enabled = true
cert_file = "{{pkg.svc_files_path}}/vault-server.pem"
key_file = "{{pkg.svc_files_path}}/vault-server-key.pem"
ca_file = "{{pkg.svc_files_path}}/ca.pem"

[ui]
enabled = true

[hab]
service_group = "vault-etcd"
