# switch this to false you want to start in DEVMODE
# https://www.vaultproject.io/intro/getting-started/dev-server.html
[dev]
mode = true

[storage]
engine = "consul"
location = "127.0.0.1"
port = "8500"
path = "vault"

[storage.tls]
enabled = false
cert_file = ""
key_file = ""
ca_file = ""

[listener]
type = "tcp"
location = "127.0.0.1"
port = "8200"
tls_disable = "1"

[listener.tls]
enabled = false
cert_file = ""
key_file = ""
ca_file = ""
min_version = "tls12"

[ui]
enabled = false

[hab]
service_group = "default"


